version: "3"

services:
  student-demo:
    image: udpp/spring-boot-cassandra-demo
    restart: always
    container_name: spring-boot-demo
    ports:
      - "8081:8081"
    networks:
      - spring-boot-cassandra-demo-network
    depends_on:
      - cassandradb

  cassandradb:
    image: udpp/my-cassandra
    container_name: cassandra-demo
    ports:
    - "9042:9042"
    networks:
      - spring-boot-cassandra-demo-network
    volumes:
      - dev-cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dev-cassandra:

networks:
  spring-boot-cassandra-demo-network: